#!/bin/bash

SCRIPT_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")/linux_bin

yad --form \
--title="WiPersona Linux Launcher" \
--width=300 --height=100 \
--field="Start server:BTN" "bash -c '$SCRIPT_DIR/launcher_linux_nogui -s'" \
--field="Stop server:BTN" "bash -c '$SCRIPT_DIR/launcher_linux_nogui -k'" \
--field="Open browser:BTN" "bash -c '$SCRIPT_DIR/launcher_linux_nogui -b'" \
--button="Exit:1"
